version: "3.7"
services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes: 
      - ${DATA}/postgres-data:/var/lib/postgresql:Z 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  spring:
    image: openjdk:17-jdk-alpine3.13
    ports: 
      - 80:8080
    volumes:
      - ./rent_car-0.0.1-SNAPSHOT.jar:/rent_car-0.0.1-SNAPSHOT.jar:ro
    entrypoint: ["java", "-jar", "/rent_car-0.0.1-SNAPSHOT.jar"]
